In [6]:
import pandas as pd
import numpy as np

from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [5]:
conc = pd.read_csv("Concrete_Data.csv")
conc

,Cement,Blast,Fly,Water,Superplasticizer,Coarse,Fine,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30
...,...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.18
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.70
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.77
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.40

In [7]:
y = conc["Strength"]
X = conc.drop("Strength", axis =1)

In [8]:

X_train, X_test, y_train, y_test = train_test_split(X,y, random_state = 24, test_size = 0.3)

In [ ]:
####################  LinearRegression  #####################

In [14]:
lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)

# we cannot use y_pred_prob in linear reg

print("the r2 score: ", r2_score(y_test,y_pred))

the r2 score:  0.5771752777048793

In [15]:
########## K-FOLD #############

In [17]:
kfold = KFold(n_splits = 5, shuffle = True, random_state = 24)
res = cross_val_score(lr,X,y,cv = kfold)
print(res.mean())

0.6066065590942402